spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
      name: ui-app
zuul:
  routes:
    admin-server:
      path: /admin/**
      url: http://admin-microservice.herokuapp.com/

    uaa-service:
      sensitiveHeaders:
      path: /uaa/**
      url: http://authorizationserver.herokuapp.com
      stripPrefix: false
  add-proxy-headers: true

security:
  oauth2:
    client:
      accessTokenUri: http://authorizationserver.herokuapp.com/uaa/oauth/token
      userAuthorizationUri: /uaa/oauth/authorize
      clientId: web-app
      clientSecret: secret
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----
      id: openid
      serviceId: ${PREFIX:}resource
      sessions: NEVER
